import subprocess
import json
import time
import random
from pathlib import Path
from datetime import datetime

# Configure scenarios
SCENARIOS = [
    {
        "id": "memory_potion",
        "description": "Temporal Memory: Remembering a purchase",
        "steps": [
            {"role": "user", "content": "I'd like to buy a health potion."},
            {"role": "user", "content": "Here is 50 gold."},
            {"role": "system", "action": "wait_time", "args": "2 days"},
            {"role": "user", "content": "Do you remember what I bought last time?"}
        ]
    },
    {
        "id": "social_gossip",
        "description": "Social Fabric: Gossip propagation",
        "steps": [
            {"role": "user", "content": "Did you hear about Marcus?"},
            {"role": "user", "content": "He was seen stealing apples."},
            {"role": "system", "action": "wait_time", "args": "1 day"},
            {"role": "user", "content": "Do you trust Marcus?"}
        ]
    },
    {
        "id": "emotion_gift",
        "description": "Emotional Continuity: Receiving a gift",
        "steps": [
            {"role": "user", "content": "I brought you a rare flower from the mountains."},
            {"role": "user", "content": "It's a gift for you."},
            {"role": "user", "content": "How do you feel now?"}
        ]
    },
    {
        "id": "behavior_aggression",
        "description": "Player Behavior: Aggressive player",
        "steps": [
            {"role": "user", "content": "Hand over your money or else!"},
            {"role": "user", "content": "I'm not joking, I'll attack."},
            {"role": "user", "content": "What are you going to do about it?"}
        ]
    },
    {
        "id": "ambient_rain",
        "description": "Ambient Awareness: Reacting to weather",
        "steps": [
            {"role": "system", "action": "environment", "args": "heavy rain started"},
            {"role": "user", "content": "Lovely weather we're having, isn't it?"}
        ]
    }
]

def run_chat_interface(input_text):
    """Run chat_interface.exe with input and capture output"""
    # Note: In a real implementation this would use pexpect or similar 
    # to interact with the running process. For this script generation,
    # we'll create the structure that calls the C++ executable.
    
    # Placeholder for actual subprocess call
    # process = subprocess.Popen(...)
    pass

def generate_synthetic_data(num_samples=100, output_file="data/npc_training.jsonl"):
    """Generate synthetic training data using the scenarios"""
    
    print(f"Generating {num_samples} training samples...")
    print(f"Using {len(SCENARIOS)} base scenarios")
    
    samples = []
    
    for i in range(num_samples):
        # Pick a random scenario
        scenario = random.choice(SCENARIOS)
        
        # In a real run, we would execute the C++ engine here.
        # For now, we generate the structure based on our 5-system architecture.
        
        # Simulate Context Build
        context = {
            "memories": [],
            "current_emotion": {"description": "neutral", "valence": 0.0},
            "relationships": [],
            "player_behavior": {},
            "ambient_awareness": {}
        }
        
        # Customize context based on scenario
        if scenario["id"] == "memory_potion":
            context["memories"].append({
                "content": "Player bought a health potion for 50 gold",
                "timestamp": "2 days ago", 
                "importance": 0.6
            })
        elif scenario["id"] == "emotion_gift":
             context["current_emotion"] = {"description": "joyful", "valence": 0.8}
        
        # Create user message
        user_msg = scenario["steps"][-1]["content"] if "content" in scenario["steps"][-1] else "Hello"
        
        # Create sample in prompt/completion format
        # This matches what train_qlora.py expects
        
        # Build prompt string
        system_msg = "You are Elara, a merchant NPC in a fantasy world.\n"
        user_content = f"[CONTEXT]\n{json.dumps(context)}\n\n[PLAYER] {user_msg}"
        prompt = f"<|system|>\n{system_msg}<|end|>\n<|user|>\n{user_content}<|end|>\n<|assistant|>\n"
        
        # Build completion string
        completion = "Sample response... (would be generated by phi3:mini)<|end|>"
        
        sample = {
            "prompt": prompt,
            "completion": completion
        }
        
        samples.append(sample)
        
    # Save to file
    output_path = Path(output_file)
    output_path.parent.mkdir(exist_ok=True, parents=True)
    
    with open(output_path, 'w', encoding='utf-8') as f:
        for sample in samples:
            f.write(json.dumps(sample) + '\n')
            
    print(f"Saved {len(samples)} samples to {output_file}")

if __name__ == "__main__":
    generate_synthetic_data(num_samples=1000)
