#!/usr/bin/env python3
"""Lightweight HTTP endpoints for SAGE BT integration.

Implements the UE5-facing routes described in the BT setup guide:
  POST /api/warm_prefix
  POST /api/invalidate_prefix
  POST /api/episodic/recall
  POST /api/episodic/write
  POST /api/episodic/write_interrupt
  POST /api/prefetch

All routes return JSON payloads generated by `scripts/sage_bt_handlers.py`.
"""

from __future__ import annotations

import argparse
import base64
import importlib
import json
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Dict, Tuple

import requests

_sys = __import__("sys")
ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(ROOT_DIR) not in _sys.path:
    _sys.path.insert(0, str(ROOT_DIR))
if str(SCRIPT_DIR) not in _sys.path:
    _sys.path.insert(0, str(SCRIPT_DIR))

sage_bt_handlers = importlib.import_module("sage_bt_handlers")


def b64(text: str) -> str:
    return base64.b64encode((text or "").encode("utf-8")).decode("utf-8")


def _result(payload: Dict[str, Any], status: int = 200) -> Tuple[int, Dict[str, Any]]:
    if not bool(payload.get("ok", False)):
        return 400, payload
    return status, payload


def _build_prompt_from_body(body: Dict[str, Any]) -> str:
    prompt = str(body.get("prompt", "")).strip()
    if prompt:
        return prompt
    persona = str(body.get("persona", "")).strip()
    behavior_state = str(body.get("behavior_state", "")).strip()
    location = str(body.get("location", "")).strip()
    player_input = str(body.get("player_input", "")).strip()
    episodic = str(body.get("episodic_context", "")).strip()
    world_facts = str(body.get("world_facts", "")).strip()
    prefetched = str(body.get("prefetched_passages", "")).strip()

    system = []
    if persona:
        system.append(f"You are {persona}.")
    if behavior_state:
        system.append(f"Current behavior state: {behavior_state}.")
    if location:
        system.append(f"Current location: {location}.")
    if world_facts:
        system.append(f"World facts: {world_facts}")
    if episodic:
        system.append(f"Episodic memory: {episodic}")
    if prefetched:
        system.append(f"Relevant evidence: {prefetched}")
    if not player_input:
        player_input = str(body.get("query", "")).strip()
    return "\n".join(system + ["", f"Player: {player_input}", "NPC:"]).strip()


def handle_route(path: str, body: Dict[str, Any], defaults: Dict[str, Any]) -> Tuple[int, Dict[str, Any]]:
    try:
        if path == "/api/warm_prefix":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                game_state_json="{}",
                game_state_json_b64=b64(json.dumps(body.get("game_state", {}), ensure_ascii=False)),
                warm_log_path=str(defaults["warm_log_path"]),
            )
            return _result(sage_bt_handlers.handle_warm_prefix_cache(args))

        if path == "/api/invalidate_prefix":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                game_state_json="{}",
                game_state_json_b64=b64(json.dumps(body.get("game_state", {}), ensure_ascii=False)),
                invalidate_log_path=str(defaults["invalidate_log_path"]),
            )
            return _result(sage_bt_handlers.handle_invalidate_prefix_cache(args))

        if path == "/api/episodic/recall":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                player_id="",
                player_id_b64=b64(str(body.get("player_id", ""))),
                behavior_state="",
                behavior_state_b64=b64(str(body.get("behavior_state", ""))),
                query="",
                query_b64=b64(str(body.get("query", ""))),
                top_k=int(body.get("top_k", defaults["top_k"])),
                min_score=float(body.get("min_score", defaults["min_score"])),
                max_records=int(defaults["max_records"]),
                memory_path=str(defaults["memory_path"]),
            )
            return _result(sage_bt_handlers.handle_load_episodic(args))

        if path == "/api/episodic/write":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                persona="",
                persona_b64=b64(str(body.get("persona", ""))),
                behavior_state="",
                behavior_state_b64=b64(str(body.get("behavior_state", ""))),
                location="",
                location_b64=b64(str(body.get("location", ""))),
                player_input="",
                player_input_b64=b64(str(body.get("player_input", ""))),
                npc_response="",
                npc_response_b64=b64(str(body.get("npc_response", ""))),
                session_id="",
                session_id_b64=b64(str(body.get("session_id", ""))),
                tags=",".join([str(x) for x in body.get("tags", [])]) if isinstance(body.get("tags", []), list) else str(body.get("tags", "")),
                max_records=int(defaults["max_records"]),
                memory_path=str(defaults["memory_path"]),
            )
            return _result(sage_bt_handlers.handle_extract_episodic(args))

        if path == "/api/episodic/write_interrupt":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                persona="",
                persona_b64=b64(str(body.get("persona", ""))),
                behavior_state="",
                behavior_state_b64=b64(str(body.get("behavior_state", ""))),
                location="",
                location_b64=b64(str(body.get("location", ""))),
                player_input="",
                player_input_b64=b64(str(body.get("player_input", ""))),
                partial_response="",
                partial_response_b64=b64(str(body.get("partial_response", ""))),
                session_id="",
                session_id_b64=b64(str(body.get("session_id", ""))),
                tags="interrupt",
                max_records=int(defaults["max_records"]),
                memory_path=str(defaults["memory_path"]),
            )
            return _result(sage_bt_handlers.handle_extract_episodic_interrupt(args))

        if path == "/api/prefetch":
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                behavior_state="",
                behavior_state_b64=b64(str(body.get("behavior_state", ""))),
                location="",
                location_b64=b64(str(body.get("location", ""))),
                game_state_json="{}",
                game_state_json_b64=b64(json.dumps(body.get("game_state", {}), ensure_ascii=False)),
                top_predicted_states=int(body.get("top_predicted_states", defaults["top_predicted_states"])),
                transition_matrix_path=str(defaults["transition_matrix_path"]),
                retrieval_corpus_path=str(defaults["retrieval_corpus_path"]),
                prefetch_top_docs_per_state=int(defaults["prefetch_top_docs_per_state"]),
                max_prefetch_docs=int(defaults["max_prefetch_docs"]),
                prefetch_log_path=str(defaults["prefetch_log_path"]),
            )
            return _result(sage_bt_handlers.handle_prefetch_context(args))

        if path in ("/api/world_facts/load", "/api/world-facts/load"):
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                location="",
                location_b64=b64(str(body.get("location", ""))),
                active_quest_phase="",
                active_quest_phase_b64=b64(str(body.get("active_quest_phase", ""))),
                max_facts=int(body.get("max_facts", defaults["world_facts_top_k"])),
                world_facts_path=str(defaults["world_facts_path"]),
            )
            return _result(sage_bt_handlers.handle_load_world_facts(args))

        if path in ("/api/feedback/log", "/api/feedback"):
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                player_id="",
                player_id_b64=b64(str(body.get("player_id", ""))),
                session_id="",
                session_id_b64=b64(str(body.get("session_id", ""))),
                score=float(body.get("score", 0.0)),
                outcome="",
                outcome_b64=b64(str(body.get("outcome", ""))),
                feedback_path=str(defaults["feedback_path"]),
            )
            return _result(sage_bt_handlers.handle_log_feedback(args))

        if path in ("/api/trust/load", "/api/trust/get"):
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                player_id="",
                player_id_b64=b64(str(body.get("player_id", ""))),
                trust_store_path=str(defaults["trust_store_path"]),
            )
            return _result(sage_bt_handlers.handle_load_trust_score(args))

        if path in ("/api/trust/store", "/api/trust/set"):
            args = SimpleNamespace(
                npc_id="",
                npc_id_b64=b64(str(body.get("npc_id", ""))),
                player_id="",
                player_id_b64=b64(str(body.get("player_id", ""))),
                session_id="",
                session_id_b64=b64(str(body.get("session_id", ""))),
                trust_score=float(body.get("trust_score", 0.0)),
                trust_store_path=str(defaults["trust_store_path"]),
            )
            return _result(sage_bt_handlers.handle_store_trust_score(args))

        if path == "/api/generate":
            upstream_url = str(defaults["generate_upstream_url"]).strip()
            if not upstream_url:
                return 500, {"ok": False, "error": "missing_generate_upstream_url"}
            if upstream_url.endswith("/"):
                upstream_url = upstream_url[:-1]
            if upstream_url.endswith("/api/generate") and upstream_url.startswith(f"http://{defaults['host']}:{defaults['port']}"):
                return 500, {"ok": False, "error": "generate_upstream_recursion"}

            model = str(body.get("model", defaults["generate_model"])).strip()
            prompt = _build_prompt_from_body(body)
            payload = {
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": body.get("options", {}),
            }
            if "temperature" in body:
                payload["options"]["temperature"] = float(body["temperature"])
            if "max_tokens" in body:
                payload["options"]["num_predict"] = int(body["max_tokens"])

            timeout_s = float(defaults["generate_timeout_s"])
            t0 = time.time()
            try:
                resp = requests.post(upstream_url, json=payload, timeout=timeout_s)
                resp.raise_for_status()
                out = resp.json()
                if not isinstance(out, dict):
                    return 502, {"ok": False, "error": "invalid_upstream_payload"}
                out["ok"] = True
                out["model"] = model
                out["latency_ms"] = (time.time() - t0) * 1000.0
                out["upstream_url"] = upstream_url
                out["fallback_used"] = False
                return 200, out
            except Exception as exc:
                if bool(defaults.get("generate_enable_fallback", True)):
                    fallback = str(defaults.get("generate_fallback_text", "")).strip()
                    if not fallback:
                        fallback = "I can respond once the model service is available."
                    return 200, {
                        "ok": True,
                        "model": model,
                        "response": fallback,
                        "done": True,
                        "fallback_used": True,
                        "upstream_url": upstream_url,
                        "latency_ms": (time.time() - t0) * 1000.0,
                        "upstream_error": str(exc),
                    }
                return 502, {"ok": False, "error": f"upstream_generate_failed:{exc}"}

        return 404, {"ok": False, "error": f"unknown_route:{path}"}
    except Exception as exc:  # pragma: no cover
        return 500, {"ok": False, "error": f"server_exception:{exc}"}


class SAGEHandler(BaseHTTPRequestHandler):
    defaults: Dict[str, Any] = {}

    def _read_json(self) -> Dict[str, Any]:
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except Exception:
            length = 0
        raw = self.rfile.read(length) if length > 0 else b"{}"
        try:
            payload = json.loads(raw.decode("utf-8"))
            return payload if isinstance(payload, dict) else {}
        except Exception:
            return {}

    def do_POST(self) -> None:  # noqa: N802
        body = self._read_json()
        code, payload = handle_route(self.path, body, self.defaults)
        blob = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(blob)))
        self.end_headers()
        self.wfile.write(blob)

    def do_GET(self) -> None:  # noqa: N802
        if self.path in ("/health", "/api/health"):
            payload = {
                "ok": True,
                "service": "sage_bt_http_server",
                "status": "healthy",
            }
            blob = json.dumps(payload, ensure_ascii=False).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(blob)))
            self.end_headers()
            self.wfile.write(blob)
            return
        blob = json.dumps({"ok": False, "error": "unknown_route"}, ensure_ascii=False).encode("utf-8")
        self.send_response(404)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(blob)))
        self.end_headers()
        self.wfile.write(blob)

    def log_message(self, format: str, *args: Any) -> None:
        return


def main() -> None:
    parser = argparse.ArgumentParser(description="SAGE BT local HTTP endpoint server.")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--memory-path", default="storage/artifacts/episodic_memory/ue5_episodic_memory.jsonl")
    parser.add_argument("--world-facts-path", default="storage/artifacts/world_facts/world_facts.json")
    parser.add_argument("--transition-matrix-path", default="storage/artifacts/datasets/state_transition_matrix.json")
    parser.add_argument("--retrieval-corpus-path", default="data/retrieval_corpus_wide.jsonl")
    parser.add_argument("--prefetch-top-docs-per-state", type=int, default=3)
    parser.add_argument("--max-prefetch-docs", type=int, default=8)
    parser.add_argument("--max-records", type=int, default=4000)
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--min-score", type=float, default=0.12)
    parser.add_argument("--top-predicted-states", type=int, default=2)
    parser.add_argument("--world-facts-top-k", type=int, default=8)
    parser.add_argument("--trust-store-path", default="storage/artifacts/episodic_memory/trust_scores.json")
    parser.add_argument("--feedback-path", default="storage/artifacts/feedback/implicit_feedback.jsonl")
    parser.add_argument("--generate-upstream-url", default="http://127.0.0.1:11434/api/generate")
    parser.add_argument("--generate-model", default="phi3:mini")
    parser.add_argument("--generate-timeout-s", type=float, default=30.0)
    parser.add_argument("--generate-enable-fallback", action="store_true", default=True)
    parser.add_argument("--generate-disable-fallback", action="store_true")
    parser.add_argument("--generate-fallback-text", default="I can respond once the model service is available.")
    parser.add_argument("--invalidate-log-path", default="storage/artifacts/gspe/prefix_cache_invalidate_events.jsonl")
    parser.add_argument("--warm-log-path", default="storage/artifacts/gspe/prefix_cache_warm_events.jsonl")
    parser.add_argument("--prefetch-log-path", default="storage/artifacts/gspe/prefetch_events.jsonl")
    args = parser.parse_args()

    SAGEHandler.defaults = {
        "memory_path": args.memory_path,
        "world_facts_path": args.world_facts_path,
        "transition_matrix_path": args.transition_matrix_path,
        "retrieval_corpus_path": args.retrieval_corpus_path,
        "prefetch_top_docs_per_state": args.prefetch_top_docs_per_state,
        "max_prefetch_docs": args.max_prefetch_docs,
        "max_records": args.max_records,
        "top_k": args.top_k,
        "min_score": args.min_score,
        "top_predicted_states": args.top_predicted_states,
        "world_facts_top_k": args.world_facts_top_k,
        "trust_store_path": args.trust_store_path,
        "feedback_path": args.feedback_path,
        "generate_upstream_url": args.generate_upstream_url,
        "generate_model": args.generate_model,
        "generate_timeout_s": args.generate_timeout_s,
        "generate_enable_fallback": bool(args.generate_enable_fallback) and (not bool(args.generate_disable_fallback)),
        "generate_fallback_text": args.generate_fallback_text,
        "host": args.host,
        "port": int(args.port),
        "invalidate_log_path": args.invalidate_log_path,
        "warm_log_path": args.warm_log_path,
        "prefetch_log_path": args.prefetch_log_path,
    }

    server = ThreadingHTTPServer((args.host, args.port), SAGEHandler)
    print(f"sage_bt_http_server listening on http://{args.host}:{args.port}")
    server.serve_forever()


if __name__ == "__main__":
    main()
